/*
 389th problem in LEETCODE  --  Find the Difference

You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
 */

public class FindTheDifference {

    static char findAns(String s1, String s2) {
        int sum = 0;
        for (char c : s2.toCharArray()) {
            sum += c;
        }
        for (char c : s1.toCharArray()) {
            sum -= c;
        }
        return (char) sum;
    }

    public static void main(String[] args) {
        String s = "abcd", t = "abcde";
        char ans = findAns(s, t);
        System.out.println("The output: " + ans);
    }
}